# Capstone II
Luis Lozada

1. Identifies which of the three proposals you outlined in your lightning talk you have chosen <br>
      <br>
    <b>Heart Disease Prediction
***
2. Articulates the main goal of your project (your problem statement) <br>
    <br>
    Heart Disease is the leading cause of death in the United States, ahead of cancer, respiratory infection, and accidents. For this reason, I think it vital to inform individuals of their risk. My goal is to great a regression model which predicts a patient's risk for heart disease given their demographic information, medical examination (blood pressure, labs, illnesses), and lifestyle (smoking, diet). 
***
3. Outlines your proposed methods and models <br>
    <br>
    All data will come from publicly available governmental sources and include demographic, locational, and self survey.
        1. Inspect datasets (and data dictionaries) for inclusion in the project
        2. If pass, preliminary cleaning, eda, sanity checks
        3. Arrive at clean dataset
        4. Build a Linear Regression Model to get a baseline
        5. Go from there... (I'm not sure what I will find so it is difficult for me to predict)
***
4. Defines the risks & assumptions of your data<br>
    <br>
    The benefit of using publicly available data is that much of it is already in CSV format. However, this implies heavy preprocessing on the hands of the primary researchers which I am not privy to. There is also the problem of selection bias when it comes to the survey data. The vast majority of data is of people which suffer from heart disease as oppossed ot healthy individuals. 
***
5. Revises initial goals & success criteria, as needed<br>
    <br>
    kk
***
6. Document your data source<br>
    <br>
    1. https://www.kaggle.com/cdc/national-health-and-nutrition-examination-survey
    2. https://chronicdata.cdc.gov/Heart-Disease-Stroke-Prevention/Behavioral-Risk-Factor-Data-Heart-Disease-Stroke-P/4ny5-qn3w
    3. https://www.kaggle.com/cdc/mortality
***
7. Performs & summarizes preliminary EDA of your data

# National Health and Nutrition Examination Survey
## NHANES datasets from 2013-2014

In [1]:
import pandas as pd

In [2]:
demographics = pd.read_csv('/Users/lu/Dropbox/Capstone/Data/national-health-and-nutrition-examination-survey/demographic.csv')

# Demographics Data Dictionary
     'SEQN' - Respondent sequence number. 
     'RIAGENDR' - Gender of participant
     'RIDAGEYR' - Age in Year, top coded 80
     'RIDAGEMN' - Age in months at time of screening, top coded 959 SO MANY NULLS
     'RIDRETH1' - Recode of reported race and Hispanic origin information
     'RIDRETH3' - Recode of reported race and Hispanic origin information, with Non-Hispanic Asian Category
     'RIDEXMON' - Six month time period when the examination was performed - two categories: November 1 through April 30, May 1 through October 31.
     'RIDEXAGM' - Age in months at time of examination
     'DMQMILIZ' - Military Service 1.0 = yes, 2.0 = no, 7.0 error? 
     'DMQADFC' - Served in foreign country during military service
     'DMDBORN4' - What country were you born, seems like the vast majority are 1 which probably means US
     'DMDCITZN' - Citizenship? 
     'DMDYRSUS' - Length of time the participant has been in the US.
     'DMDEDUC3' - 
     'DMDEDUC2',
     'DMDMARTL',
     'RIDEXPRG',
     'SIALANG' - Language used for sampling
     'SIAPROXY' - language proxy
     'SIAINTRP' - interpretor used
     'FIALANG' - family interview language
     'FIAPROXY' - proxy used for family interview
     'FIAINTRP' - interpretor used for family
     'MIALANG',
     'MIAPROXY',
     'MIAINTRP',
     'AIALANGA',
     'DMDHHSIZ' - Total number of people in household 
     'DMDFMSIZ' - Total number of people in family
     'DMDHHSZA'- num children >=5 in household
     'DMDHHSZB' - num children 6-17 in household
     'DMDHHSZE',
     'DMDHRGND',
     'DMDHRAGE',
     'DMDHRBR4',
     'DMDHREDU',
     'DMDHRMAR',
     'DMDHSEDU',
     'WTINT2YR',
     'WTMEC2YR',
     'SDMVPSU',
     'SDMVSTRA',
     'INDHHIN2',
     'INDFMIN2',
     'INDFMPIR']

In [3]:
list(demographics.columns[(demographics.isnull().sum() > 1000)]) # more than 1000 nulls in column

['RIDAGEMN',
 'RIDEXAGM',
 'DMQMILIZ',
 'DMQADFC',
 'DMDYRSUS',
 'DMDEDUC3',
 'DMDEDUC2',
 'DMDMARTL',
 'RIDEXPRG',
 'MIALANG',
 'MIAPROXY',
 'MIAINTRP',
 'AIALANGA',
 'DMDHSEDU']

In [4]:
demographics[demographics.columns[(demographics.isnull().sum() > 1000)]].head()

,RIDAGEMN,RIDEXAGM,DMQMILIZ,DMQADFC,DMDYRSUS,DMDEDUC3,DMDEDUC2,DMDMARTL,RIDEXPRG,MIALANG,MIAPROXY,MIAINTRP,AIALANGA,DMDHSEDU
0,NaN,NaN,1.0,1.0,NaN,NaN,3.0,4.0,NaN,1.0,2.0,2.0,1.0,NaN
1,NaN,NaN,2.0,NaN,NaN,NaN,3.0,1.0,NaN,1.0,2.0,2.0,1.0,1.0
2,NaN,NaN,1.0,1.0,NaN,NaN,4.0,1.0,NaN,1.0,2.0,2.0,NaN,3.0
3,NaN,119.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,1.0,2.0,2.0,1.0,4.0
4,NaN,NaN,2.0,NaN,NaN,NaN,5.0,1.0,NaN,1.0,2.0,2.0,NaN,5.0

In [5]:
demographics.drop(demographics.columns[(demographics.isnull().sum() > 1000)], axis=1, inplace=True) #dropping all columns with over 1k nulls

In [6]:
list(demographics.columns)

['SEQN',
 'SDDSRVYR',
 'RIDSTATR',
 'RIAGENDR',
 'RIDAGEYR',
 'RIDRETH1',
 'RIDRETH3',
 'RIDEXMON',
 'DMDBORN4',
 'DMDCITZN',
 'SIALANG',
 'SIAPROXY',
 'SIAINTRP',
 'FIALANG',
 'FIAPROXY',
 'FIAINTRP',
 'DMDHHSIZ',
 'DMDFMSIZ',
 'DMDHHSZA',
 'DMDHHSZB',
 'DMDHHSZE',
 'DMDHRGND',
 'DMDHRAGE',
 'DMDHRBR4',
 'DMDHREDU',
 'DMDHRMAR',
 'WTINT2YR',
 'WTMEC2YR',
 'SDMVPSU',
 'SDMVSTRA',
 'INDHHIN2',
 'INDFMIN2',
 'INDFMPIR']

In [7]:
important_demo = ['SEQN', 'RIAGENDR', 'RIDAGEYR', 'RIDRETH1', 'RIDRETH3', 'RIDEXMON', 'DMDBORN4', 'DMDCITZN', 'SIALANG', 'SIAINTRP', 'FIALANG',
                 'FIAPROXY', 'FIAINTRP', 'DMDHHSIZ', 'DMDHHSZA', 'DMDHHSZB', '']

In [8]:
demographics['FIALANG'].value_counts() # family

1.0    9417
2.0     637
Name: FIALANG, dtype: int64

In [9]:
demographics['SIAINTRP'].value_counts() #was an interpretor used?

2    9833
1     342
Name: SIAINTRP, dtype: int64

In [10]:
demographics['SIALANG'].value_counts() # language of screening

1    9100
2    1075
Name: SIALANG, dtype: int64

In [11]:
demographics['DMDCITZN'].value_counts() # maybe a citizenship questions?

1.0    9220
2.0     944
7.0       4
9.0       3
Name: DMDCITZN, dtype: int64

In [12]:
# these are columns I intend to drop wholesale 
to_drop = ['SDDSRVYR', 'RIDSTATR', 'RIDAGEMN', 'DMQADFC', 'DMDYRSUS', ]

In [13]:
demographics['DMQMILIZ'].value_counts() 
# 2.0 = no
# 1.0 = yes
# one error

KeyError: 'DMQMILIZ'

In [15]:
demographics[(demographics['DMQMILIZ'] == 7.0)] # error at index = 5275

In [16]:
demographics['DMQADFC'].value_counts()

KeyError: 'DMQADFC'

In [17]:
demographics['DMDBORN4'].value_counts()

1     8262
2     1908
77       4
99       1
Name: DMDBORN4, dtype: int64

In [86]:
demographics['DMDYRSUS'].value_counts()

6.0     342
4.0     298
7.0     246
3.0     234
5.0     210
2.0     170
8.0     146
9.0     106
1.0      70
99.0     45
77.0     41
Name: DMDYRSUS, dtype: int64

[9.0     44
 6.0     44
 1.0     42
 8.0     39
 5.0     38
 4.0     33
 7.0     32
 10.0    31
 23.0    30
 15.0    29
 0.0     28
 3.0     28
 13.0    27
 2.0     26
 18.0    25
 17.0    24
 22.0    22
 16.0    21
 12.0    20
 11.0    20
 20.0    18
 21.0    16
 14.0    16
 19.0    12
 24.0     8
 Name: RIDAGEMN, dtype: int64, 5.0      43
 7.0      40
 2.0      39
 6.0      37
 10.0     37
 34.0     36
 9.0      35
 8.0      34
 16.0     32
 119.0    31
 1.0      30
 11.0     29
 144.0    27
 153.0    27
 24.0     27
 86.0     26
 91.0     25
 128.0    25
 27.0     25
 47.0     25
 163.0    24
 52.0     24
 66.0     24
 96.0     24
 107.0    24
 170.0    24
 193.0    24
 23.0     24
 142.0    23
 78.0     23
          ..
 186.0    11
 222.0    11
 179.0    11
 152.0    11
 136.0    11
 54.0     11
 202.0    10
 37.0     10
 156.0    10
 215.0    10
 209.0    10
 197.0    10
 167.0     9
 149.0     9
 227.0     9
 63.0      9
 210.0     8
 191.0     8
 160.0     8
 225.0     8
 165.0     8
 235.0     8
 228.0     7
 206.0     7
 90.0      6
 207.0     6
 154.0     6
 230.0     5
 46.0      5
 0.0       4
 Name: RIDEXAGM, Length: 240, dtype: int64, 2.0    5717
 1.0     543
 7.0       1
 Name: DMQMILIZ, dtype: int64, 1.0    282
 2.0    260
 9.0      1
 Name: DMQADFC, dtype: int64, 6.0     342
 4.0     298
 7.0     246
 3.0     234
 5.0     210
 2.0     170
 8.0     146
 9.0     106
 1.0      70
 99.0     45
 77.0     41
 Name: DMDYRSUS, dtype: int64, 0.0     277
 1.0     237
 4.0     234
 2.0     231
 3.0     215
 5.0     212
 7.0     203
 9.0     194
 8.0     189
 11.0    186
 6.0     178
 10.0    162
 13.0    137
 15.0     81
 12.0     45
 14.0      9
 66.0      9
 55.0      3
 99.0      1
 Name: DMDEDUC3, dtype: int64, 4.0    1770
 5.0    1443
 3.0    1303
 2.0     791
 1.0     455
 9.0       5
 7.0       2
 Name: DMDEDUC2, dtype: int64, 1.0     2965
 5.0     1112
 3.0      659
 2.0      436
 6.0      417
 4.0      177
 77.0       2
 99.0       1
 Name: DMDMARTL, dtype: int64, 2.0    1150
 3.0      94
 1.0      65
 Name: RIDEXPRG, dtype: int64, 1.0    6904
 2.0     407
 Name: MIALANG, dtype: int64, 2.0    7264
 1.0      48
 Name: MIAPROXY, dtype: int64, 2.0    7066
 1.0     247
 Name: MIAINTRP, dtype: int64, 1.0    5762
 2.0     482
 3.0      73
 Name: AIALANGA, dtype: int64, 5.0    1664
 4.0    1470
 3.0    1063
 2.0     632
 1.0     496
 9.0      16
 7.0       1
 Name: DMDHSEDU, dtype: int64]

In [77]:
list(demographics.columns[(demographics.isnull().sum() > 1000)])

['RIDAGEMN',
 'RIDEXAGM',
 'DMQMILIZ',
 'DMQADFC',
 'DMDYRSUS',
 'DMDEDUC3',
 'DMDEDUC2',
 'DMDMARTL',
 'RIDEXPRG',
 'MIALANG',
 'MIAPROXY',
 'MIAINTRP',
 'AIALANGA',
 'DMDHSEDU']

In [18]:
diet = pd.read_csv('/Users/lu/Dropbox/Capstone/Data/national-health-and-nutrition-examination-survey/diet.csv')

In [19]:
exam = pd.read_csv('/Users/lu/Dropbox/Capstone/Data/national-health-and-nutrition-examination-survey/examination.csv')

In [20]:
labs = pd.read_csv('/Users/lu/Dropbox/Capstone/Data/national-health-and-nutrition-examination-survey/labs.csv')

In [21]:
meds = pd.read_csv('/Users/lu/Dropbox/Capstone/Data/national-health-and-nutrition-examination-survey/medications.csv', encoding='unicode_escape')

In [22]:
questionnaire = pd.read_csv('/Users/lu/Dropbox/Capstone/Data/national-health-and-nutrition-examination-survey/questionnaire.csv')

In [10]:
data = [demographics, diet, exam, labs, meds, questionnaire]

In [11]:
for each in data:
    print(each.shape)

(10175, 47)
(9813, 168)
(9813, 224)
(9813, 424)
(20194, 13)
(10175, 953)

In [27]:
(demographics.columns) & (diet.columns) & (exam.columns) & (labs.columns) & (meds.columns) & (questionnaire.columns)

Index(['SEQN'], dtype='object')

In [46]:
demographics

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,DMDHREDU,DMDHRMAR,DMDHSEDU,WTINT2YR,WTMEC2YR,SDMVPSU,SDMVSTRA,INDHHIN2,INDFMIN2,INDFMPIR
0,73557,8,2,1,69,NaN,4,4,1.0,NaN,...,3.0,4.0,NaN,13281.237386,13481.042095,1,112,4.0,4.0,0.84
1,73558,8,2,1,54,NaN,3,3,1.0,NaN,...,3.0,1.0,1.0,23682.057386,24471.769625,1,108,7.0,7.0,1.78
2,73559,8,2,1,72,NaN,3,3,2.0,NaN,...,4.0,1.0,3.0,57214.803319,57193.285376,1,109,10.0,10.0,4.51
3,73560,8,2,1,9,NaN,3,3,1.0,119.0,...,3.0,1.0,4.0,55201.178592,55766.512438,2,109,9.0,9.0,2.52
4,73561,8,2,2,73,NaN,3,3,1.0,NaN,...,5.0,1.0,5.0,63709.667069,65541.871229,2,116,15.0,15.0,5.00
5,73562,8,2,1,56,NaN,1,1,1.0,NaN,...,4.0,3.0,NaN,24978.144602,25344.992359,1,111,9.0,9.0,4.79
6,73563,8,2,1,0,5.0,3,3,2.0,6.0,...,5.0,1.0,5.0,18040.818432,17913.555067,1,105,15.0,15.0,5.00
7,73564,8,2,2,61,NaN,3,3,2.0,NaN,...,5.0,2.0,NaN,60325.095254,61758.654880,1,114,10.0,10.0,5.00
8,73565,8,1,1,42,NaN,2,2,NaN,NaN,...,3.0,1.0,5.0,23307.675629,0.000000,2,106,15.0,15.0,5.00
9,73566,8,2,2,56,NaN,3,3,1.0,NaN,...,3.0,3.0,NaN,16351.783140,17480.115175,1,112,4.0,4.0,0.48
10,73567,8,2,1,65,NaN,3,3,2.0,NaN,...,2.0,2.0,NaN,34002.622995,34795.429301,2,112,3.0,3.0,1.20
11,73568,8,2,2,26,NaN,3,3,2.0,NaN,...,5.0,5.0,NaN,89514.433218,91523.516048,2,113,15.0,15.0,5.00
12,73569,8,1,2,0,10.0,5,7,NaN,NaN,...,4.0,1.0,5.0,6673.803649,0.000000,1,110,77.0,77.0,NaN
13,73570,8,2,2,9,NaN,5,7,1.0,109.0,...,5.0,3.0,NaN,11913.818655,12071.467415,2,115,5.0,5.0,0.84
14,73571,8,2,1,76,NaN,3,3,1.0,NaN,...,5.0,1.0,5.0,46988.470276,46190.114005,1,116,14.0,14.0,5.00
15,73572,8,2,2,10,NaN,4,4,1.0,125.0,...,4.0,5.0,NaN,11689.376908,12764.396165,2,111,2.0,2.0,0.41
16,73573,8,2,1,10,NaN,4,4,1.0,128.0,...,3.0,1.0,3.0,6403.212786,6460.787962,2,106,8.0,8.0,1.79
17,73574,8,2,2,33,NaN,5,6,1.0,NaN,...,5.0,1.0,5.0,14155.313000,15397.219846,2,114,8.0,8.0,2.10
18,73575,8,2,1,1,18.0,4,4,1.0,19.0,...,2.0,NaN,NaN,7574.950558,7721.542396,2,116,3.0,3.0,0.76
19,73576,8,2,1,16,NaN,4,4,2.0,194.0,...,4.0,77.0,NaN,12433.748735,12665.770090,1,104,8.0,8.0,1.58
20,73577,8,2,1,32,NaN,1,1,1.0,NaN,...,3.0,6.0,NaN,36284.650273,39735.017070,2,118,5.0,2.0,0.29
21,73578,8,2,1,18,NaN,1,1,1.0,218.0,...,3.0,1.0,1.0,11592.846429,11758.631127,2,118,5.0,5.0,0.58
22,73579,8,2,2,12,NaN,3,3,2.0,147.0,...,5.0,1.0,5.0,63248.989522,70708.034030,1,110,10.0,10.0,2.97
23,73580,8,2,2,38,NaN,4,4,1.0,NaN,...,3.0,1.0,2.0,27388.920690,27196.638394,2,116,12.0,12.0,NaN
24,73581,8,2,1,50,NaN,5,6,1.0,NaN,...,5.0,1.0,4.0,15902.418122,16764.260669,2,106,15.0,15.0,5.00
25,73582,8,2,2,23,NaN,4,4,1.0,NaN,...,4.0,6.0,NaN,30197.081366,31181.886343,1,108,3.0,3.0,0.69
26,73583,8,2,2,7,NaN,3,3,2.0,86.0,...,5.0,1.0,5.0,47574.649392,48196.409412,1,110,15.0,15.0,5.00
27,73584,8,2,1,13,NaN,3,3,2.0,158.0,...,4.0,1.0,NaN,72700.381729,72182.239545,1,105,9.0,9.0,3.07
28,73585,8,2,1,28,NaN,5,6,2.0,NaN,...,4.0,1.0,4.0,18063.143861,18590.965473,1,110,7.0,7.0,2.26
29,73586,8,2,2,4,NaN,5,6,1.0,58.0,...,4.0,1.0,4.0,11635.240800,13569.677359,1,116,6.0,6.0,1.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10145,83702,8,2,2,80,NaN,3,3,1.0,NaN,...,4.0,2.0,NaN,31569.274135,33466.362531,1,112,7.0,7.0,3.57
10146,83703,8,2,1,22,NaN,1,1,2.0,NaN,...,2.0,1.0,2.0,40362.045231,42187.066631,1,106,99.0,99.0,NaN
10147,83704,8,2,1,15,NaN,3,3,2.0,182.0,...,4.0,1.0,NaN,22410.160297,22250.441062,1,104,1.0,1.0,0.00
10148,83705,8,2,2,35,NaN,2,2,1.0,NaN,...,3.0,6.0,NaN,34093.594033,33825.411466,1,108,4.0,4.0,0.58
10149,83706,8,2,2,6,NaN,4,4,2.0,80.0,...,4.0,5.0,NaN,8662.610109,8648.548981,1,114,6.0,6.0,1.36
10150,83707,8,2,1,18,NaN,1,1,2.0,219.0,...,2.0,NaN,NaN,18081.800286,18481.068602,2,108,12.0,3.0,0.86
10151,83708,8,2,1,64,NaN,3,3,1.0,NaN,...,3.0,3.0,NaN,100202.168410,102106.493777,1,112,5.0,5.0,2.09
10152,83709,8,2,1,24,NaN,3,3,1.0,NaN,...,1.0,1.0,1.0,84539.996864,86433.720386,1,113,15.0,15.0,3.63
10153,83710,8,2,2,2,NaN,4,4,1.0,25.0,...,4.0,5.0,NaN,7371.222940,7630.076690,2,114,1.0,1.0,0.11
10154,83711,8,2,2,38,NaN,3,3,1.0,NaN,...,4.0,1.0,4.0,28291.516598,28736.069266,2,109,7.0,7.0,1.08
10155,83712,8,2,1,61,NaN,3,3,1.0,NaN,...,2.0,1.0,4.0,38081.290660,38231.457622,2,115,9.0,9.0,2.04
10156,83713,8,2,1,34,NaN,5,6,1.0,NaN,...,4.0,1.0,4.0,14919.218779,16535.236604,2,118,6.0,6.0,1.27
10157,83714,8,2,2,19,NaN,3,3,2.0,231.0,...,2.0,6.0,NaN,26001.173776,26632.551922,1,114,6.0,6.0,1.20
10158,83715,8,2,1,58,NaN,3,3,1.0,NaN,...,1.0,5.0,NaN,25819.771131,27756.512614,2,116,3.0,3.0,0.94
10159,83716,8,2,1,17,NaN,3,3,1.0,215.0,...,4.0,1.0,4.0,49146.845584,50054.337936,1,116,15.0,15.0,3.63
10160,83717,8,2,2,80,NaN,1,1,2.0,NaN,...,3.0,1.0,NaN,12010.325301,12031.439724,1,107,6.0,6.0,0.70
10161,83718,8,2,2,60,NaN,4,4,2.0,NaN,...,3.0,2.0,NaN,34902.817661,37866.383266,1,113,NaN,NaN,NaN
10162,83719,8,2,1,3,NaN,1,1,1.0,42.0,...,3.0,6.0,NaN,23018.846097,24135.493026,1,106,8.0,8.0,2.32
10163,83720,8,2,1,36,NaN,4,4,1.0,NaN,...,4.0,5.0,NaN,20917.413262,22721.755013,1,112,8.0,8.0,2.90
10164,83721,8,2,1,52,NaN,3,3,1.0,NaN,...,5.0,1.0,5.0,67937.153461,68456.771849,1,112,15.0,15.0,5.00
10165,83722,8,2,1,0,0.0,5,7,2.0,2.0,...,3.0,6.0,NaN,4732.381343,4932.794501,2,105,7.0,7.0,0.97
10166,83723,8,2,1,61,NaN,1,1,2.0,NaN,...,2.0,1.0,3.0,11140.687817,11179.994842,1,109,10.0,10.0,3.53
10167,83724,8,2,1,80,NaN,3,3,1.0,NaN,...,3.0,1.0,4.0,28323.849076,29383.486541,1,117,8.0,8.0,3.09
10168,83725,8,2,1,7,NaN,1,1,1.0,95.0,...,4.0,4.0,NaN,20425.791465,20632.950468,1,106,6.0,6.0,1.07
10169,83726,8,2,1,40,NaN,1,1,1.0,NaN,...,1.0,3.0,NaN,45268.572702,49177.291000,2,115,9.0,9.0,3.81
10170,83727,8,2,1,26,NaN,2,2,2.0,NaN,...,3.0,NaN,NaN,27141.631824,28115.568221,1,104,77.0,77.0,NaN
10171,83728,8,2,2,2,24.0,1,1,2.0,24.0,...,3.0,1.0,3.0,15274.475360,16512.138781,1,107,8.0,8.0,1.95
10172,83729,8,2,2,42,NaN,4,4,2.0,NaN,...,5.0,3.0,NaN,24122.248900,26902.344381,1,104,7.0,7.0,3.66
10173,83730,8,2,1,7,NaN,2,2,1.0,84.0,...,4.0,1.0,3.0,25521.878546,26686.025573,2,109,6.0,6.0,1.05
10174,83731,8,2,1,11,NaN,5,6,1.0,140.0,...,5.0,1.0,5.0,8930.180154,9700.873491,2,106,15.0,15.0,5.00

In [50]:
demodiet = pd.merge(demographics, diet, on='SEQN')

In [51]:
pd.merge(demodiet, exam, on='SEQN')

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,CSXLEAOD,CSXSOAOD,CSXGRAOD,CSXONOD,CSXNGSOD,CSXSLTRT,CSXSLTRG,CSXNART,CSXNARG,CSAEFFRT
0,73557,8,2,1,69,NaN,4,4,1.0,NaN,...,2.0,1.0,1.0,1.0,4.0,62.0,1.0,NaN,NaN,1.0
1,73558,8,2,1,54,NaN,3,3,1.0,NaN,...,3.0,1.0,2.0,3.0,4.0,28.0,1.0,NaN,NaN,1.0
2,73559,8,2,1,72,NaN,3,3,2.0,NaN,...,2.0,1.0,2.0,3.0,4.0,49.0,1.0,NaN,NaN,3.0
3,73560,8,2,1,9,NaN,3,3,1.0,119.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,73561,8,2,2,73,NaN,3,3,1.0,NaN,...,3.0,1.0,4.0,3.0,4.0,NaN,NaN,NaN,NaN,1.0
5,73562,8,2,1,56,NaN,1,1,1.0,NaN,...,3.0,1.0,2.0,3.0,4.0,21.0,1.0,NaN,NaN,1.0
6,73563,8,2,1,0,5.0,3,3,2.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,73564,8,2,2,61,NaN,3,3,2.0,NaN,...,3.0,1.0,2.0,3.0,4.0,NaN,NaN,12.0,1.0,1.0
8,73566,8,2,2,56,NaN,3,3,1.0,NaN,...,3.0,1.0,2.0,3.0,4.0,NaN,NaN,20.0,1.0,1.0
9,73567,8,2,1,65,NaN,3,3,2.0,NaN,...,3.0,1.0,2.0,3.0,4.0,NaN,NaN,54.0,1.0,1.0
10,73568,8,2,2,26,NaN,3,3,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,73570,8,2,2,9,NaN,5,7,1.0,109.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,73571,8,2,1,76,NaN,3,3,1.0,NaN,...,3.0,1.0,2.0,3.0,4.0,NaN,NaN,45.0,1.0,1.0
13,73572,8,2,2,10,NaN,4,4,1.0,125.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,73573,8,2,1,10,NaN,4,4,1.0,128.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,73574,8,2,2,33,NaN,5,6,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,73575,8,2,1,1,18.0,4,4,1.0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,73576,8,2,1,16,NaN,4,4,2.0,194.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,73577,8,2,1,32,NaN,1,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,73578,8,2,1,18,NaN,1,1,1.0,218.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,73579,8,2,2,12,NaN,3,3,2.0,147.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,73580,8,2,2,38,NaN,4,4,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,73581,8,2,1,50,NaN,5,6,1.0,NaN,...,3.0,1.0,2.0,3.0,4.0,93.0,1.0,NaN,NaN,1.0
23,73582,8,2,2,23,NaN,4,4,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,73583,8,2,2,7,NaN,3,3,2.0,86.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,73584,8,2,1,13,NaN,3,3,2.0,158.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,73585,8,2,1,28,NaN,5,6,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,73586,8,2,2,4,NaN,5,6,1.0,58.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,73587,8,2,1,14,NaN,5,6,1.0,174.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,73588,8,2,1,11,NaN,4,4,1.0,140.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9783,83702,8,2,2,80,NaN,3,3,1.0,NaN,...,3.0,1.0,2.0,3.0,4.0,93.0,1.0,NaN,NaN,3.0
9784,83703,8,2,1,22,NaN,1,1,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9785,83704,8,2,1,15,NaN,3,3,2.0,182.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9786,83705,8,2,2,35,NaN,2,2,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9787,83706,8,2,2,6,NaN,4,4,2.0,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9788,83707,8,2,1,18,NaN,1,1,2.0,219.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9789,83708,8,2,1,64,NaN,3,3,1.0,NaN,...,1.0,1.0,3.0,4.0,4.0,15.0,1.0,NaN,NaN,3.0
9790,83709,8,2,1,24,NaN,3,3,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9791,83710,8,2,2,2,NaN,4,4,1.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9792,83711,8,2,2,38,NaN,3,3,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9793,83712,8,2,1,61,NaN,3,3,1.0,NaN,...,3.0,1.0,2.0,3.0,4.0,60.0,1.0,NaN,NaN,1.0
9794,83713,8,2,1,34,NaN,5,6,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9795,83714,8,2,2,19,NaN,3,3,2.0,231.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9796,83715,8,2,1,58,NaN,3,3,1.0,NaN,...,3.0,1.0,2.0,3.0,4.0,NaN,NaN,5.0,1.0,4.0
9797,83716,8,2,1,17,NaN,3,3,1.0,215.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9798,83717,8,2,2,80,NaN,1,1,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9799,83718,8,2,2,60,NaN,4,4,2.0,NaN,...,3.0,1.0,3.0,3.0,4.0,NaN,NaN,NaN,NaN,3.0
9800,83719,8,2,1,3,NaN,1,1,1.0,42.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9801,83720,8,2,1,36,NaN,4,4,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9802,83721,8,2,1,52,NaN,3,3,1.0,NaN,...,3.0,1.0,2.0,3.0,1.0,NaN,NaN,45.0,1.0,1.0
9803,83722,8,2,1,0,0.0,5,7,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9804,83723,8,2,1,61,NaN,1,1,2.0,NaN,...,3.0,1.0,2.0,3.0,4.0,NaN,NaN,15.0,1.0,2.0
9805,83724,8,2,1,80,NaN,3,3,1.0,NaN,...,3.0,1.0,4.0,3.0,1.0,20.0,1.0,NaN,NaN,1.0
9806,83725,8,2,1,7,NaN,1,1,1.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9807,83726,8,2,1,40,NaN,1,1,1.0,NaN,...,1.0,1.0,2.0,3.0,4.0,NaN,NaN,43.0,1.0,1.0
9808,83727,8,2,1,26,NaN,2,2,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9809,83728,8,2,2,2,24.0,1,1,2.0,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9810,83729,8,2,2,42,NaN,4,4,2.0,NaN,...,1.0,1.0,1.0,3.0,4.0,55.0,1.0,NaN,NaN,3.0
9811,83730,8,2,1,7,NaN,2,2,1.0,84.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9812,83731,8,2,1,11,NaN,5,6,1.0,140.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Behavioral Risk Factor Data: Heart Disease & Stroke Prevention
CDC

In [12]:
df = pd.read_csv('/Users/lu/Dropbox/Capstone/Data/dataset.csv')

In [13]:
df.head()

,Year,LocationAbbr,LocationDesc,Datasource,PriorityArea1,PriorityArea2,PriorityArea3,PriorityArea4,Category,Topic,...,Break_Out_Category,Break_out,CategoryID,TopicID,IndicatorID,Data_Value_TypeID,BreakoutCategoryID,BreakOutID,LocationID,GeoLocation
0,2011,AL,Alabama,BRFSS,None,None,None,None,Cardiovascular Diseases,Major Cardiovascular Disease,...,Overall,Overall,C1,T1,BR001,AgeStdz,BOC01,OVR01,1,"(32.84057112200048, -86.63186076199969)"
1,2011,AL,Alabama,BRFSS,None,None,None,None,Cardiovascular Diseases,Major Cardiovascular Disease,...,Overall,Overall,C1,T1,BR001,Crude,BOC01,OVR01,1,"(32.84057112200048, -86.63186076199969)"
2,2011,AL,Alabama,BRFSS,None,None,None,None,Cardiovascular Diseases,Major Cardiovascular Disease,...,Gender,Male,C1,T1,BR001,Crude,BOC02,GEN01,1,"(32.84057112200048, -86.63186076199969)"
3,2011,AL,Alabama,BRFSS,None,None,None,None,Cardiovascular Diseases,Major Cardiovascular Disease,...,Gender,Male,C1,T1,BR001,AgeStdz,BOC02,GEN01,1,"(32.84057112200048, -86.63186076199969)"
4,2011,AL,Alabama,BRFSS,None,None,None,None,Cardiovascular Diseases,Major Cardiovascular Disease,...,Gender,Female,C1,T1,BR001,AgeStdz,BOC02,GEN02,1,"(32.84057112200048, -86.63186076199969)"

In [14]:
list(df.columns)

['Year',
 'LocationAbbr',
 'LocationDesc',
 'Datasource',
 'PriorityArea1',
 'PriorityArea2',
 'PriorityArea3',
 'PriorityArea4',
 'Category',
 'Topic',
 'Indicator',
 'Data_Value_Type',
 'Data_Value_Unit',
 'Data_Value',
 'Data_Value_Alt',
 'Data_Value_Footnote_Symbol',
 'Data_Value_Footnote',
 'Confidence_Limit_Low',
 'Confidence_Limit_High',
 'Break_Out_Category',
 'Break_out',
 'CategoryID',
 'TopicID',
 'IndicatorID',
 'Data_Value_TypeID',
 'BreakoutCategoryID',
 'BreakOutID',
 'LocationID',
 'GeoLocation']

In [14]:
df['Data_Value_Type'].value_counts()

Crude               54600
Age-Standardized    31200
Name: Data_Value_Type, dtype: int64

In [15]:
df['Data_Value_Unit'].value_counts()

Percent (%)    85800
Name: Data_Value_Unit, dtype: int64

# Mortality
CDC

In [16]:
# mort15 = pd.read_csv('./mortality/2015_data.csv')

# mort14 = pd.read_csv('./mortality/2014_data.csv')

# mort13 = pd.read_csv('./mortality/2013_data.csv')

# mort12 = pd.read_csv('./mortality/2012_data.csv')

# mort11 = pd.read_csv('./mortality/2011_data.csv')